import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        // Material-3 "FinAccord/Discovery" design system.
        // `primary` keeps its legacy numeric scale (used by older components)
        // AND gains a DEFAULT + named variants for the new design.
        primary: {
          DEFAULT: "#002045",
          container: "#1a365d",
          fixed: "#d6e3ff",
          "fixed-dim": "#adc7f7",
          50: "#f0f9ff",
          100: "#e0f2fe",
          200: "#bae6fd",
          300: "#7dd3fc",
          400: "#38bdf8",
          500: "#0ea5e9",
          600: "#0284c7",
          700: "#0369a1",
          800: "#075985",
          900: "#0c4a6e",
        },
        secondary: {
          DEFAULT: "#0a6c44",
          container: "#9ff5c1",
          fixed: "#9ff5c1",
          "fixed-dim": "#83d8a6",
        },
        "on-primary": "#ffffff",
        "on-primary-container": "#86a0cd",
        "on-primary-fixed": "#001b3c",
        "on-primary-fixed-variant": "#2d476f",
        "on-secondary": "#ffffff",
        "on-secondary-container": "#167249",
        "on-secondary-fixed": "#002111",
        "on-secondary-fixed-variant": "#005231",
        "tertiary-fixed": "#ffdeaa",
        "tertiary-fixed-dim": "#f8bc4b",
        "on-tertiary-fixed": "#271900",
        "on-tertiary-fixed-variant": "#5f4100",
        background: "#f7fafc",
        surface: "#f7fafc",
        "surface-bright": "#f7fafc",
        "surface-border": "#E2E8F0",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f1f4f6",
        "surface-container": "#ebeef0",
        "surface-container-high": "#e5e9eb",
        "surface-container-highest": "#e0e3e5",
        "on-surface": "#181c1e",
        "on-surface-variant": "#43474e",
        outline: "#74777f",
        "outline-variant": "#c4c6cf",
        "status-warning": "#D69E2E",
        "status-positive": "#2F855A",
        "status-neutral": "#4A5568",
        "text-main": "#2D3748",
        error: "#ba1a1a",
        "error-container": "#ffdad6",
        "on-error": "#ffffff",
        "on-error-container": "#93000a",
      },
      spacing: {
        unit: "4px",
        "stack-sm": "8px",
        "stack-md": "16px",
        "stack-lg": "32px",
        gutter: "24px",
        "margin-mobile": "20px",
        "margin-desktop": "64px",
      },
      maxWidth: {
        "container-max": "1200px",
      },
      fontFamily: {
        sans: ["Public Sans", "ui-sans-serif", "system-ui", "sans-serif"],
        "display-lg": ["Public Sans", "sans-serif"],
        "headline-lg": ["Public Sans", "sans-serif"],
        "headline-md": ["Public Sans", "sans-serif"],
        "body-lg": ["Public Sans", "sans-serif"],
        "body-md": ["Public Sans", "sans-serif"],
        "label-md": ["Public Sans", "sans-serif"],
        "label-sm": ["Public Sans", "sans-serif"],
      },
      fontSize: {
        "display-lg": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.01em", fontWeight: "700" }],
        "headline-lg-mobile": ["24px", { lineHeight: "32px", fontWeight: "700" }],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "label-md": ["14px", { lineHeight: "20px", letterSpacing: "0.01em", fontWeight: "600" }],
        "label-sm": ["12px", { lineHeight: "16px", fontWeight: "500" }],
      },
    },
  },
  plugins: [],
};
export default config;
